module.exports = {
  apps: [{
    script: 'bin/www',
    name: 'vebusapiv3',
    // instances: '1',
    // exec_mode: 'cluster',
    autorestart: true,
    env_development: {
      BOT_TOKEN: '6439712622:AAGRWQow3jXzof9Ss-HhqLq6kQwslAIKmig',
      BOT_CHAT_ID: '-937486602',
      DB_HOST_CONFIG: '192.168.1.215',
      DB_PORT_CONFIG: 3306,
      DB_NAME_CONFIG: 'vebus_config',
      DB_USER_CONFIG: 'vdsi',
      DB_PASS_CONFIG: 'Vdsi@2023',
      DB_HOST_WRITE: '192.168.1.215',
      DB_PORT_WRITE: 3306,
      DB_NAME_WRITE: 'vebus_log',
      DB_USER_WRITE: 'vdsi',
      DB_PASS_WRITE: 'Vdsi@2023',
      DB_HOST_READ: '192.168.1.215',
      DB_PORT_READ: '3306',
      DB_NAME_READ: 'vebus_log',
      DB_USER_READ: 'vdsi',
      DB_PASS_READ: 'Vdsi@2023',
      DB_HOST_INVOICE: '192.168.1.215',
      DB_PORT_INVOICE: '3306',
      DB_NAME_INVOICE: 'vebus_invoice',
      DB_USER_INVOICE: 'vdsi',
      DB_PASS_INVOICE: 'Vdsi@2023',
      ENV: 'staging',
      API_KEY: '980alsdfja!^&%%KJBKu',
      RABBITMQ_HOST: '192.168.1.215',
      RABBITMQ_PORT: 5672,
      RABBITMQ_USERNAME: 'vdsi_queue',
      RABBITMQ_PASSWORD: 'Vdsi@2023',
      OperatorSyncBusTicketStartEndPointTopic: 'VeBus.OperatorSync.BusTicketStartEndPointTopic_V1',
      OperatorSyncBusTicketPointTopic: 'VeBus.OperatorSync.BusTicketPointTopic_V1',
      OperatorSyncTopic: 'VeBus.OperatorSyncTopic_V1',
      InvoiceSyncTopicB1: 'VeBus.InvoiceSyncB1_V1',
      MissingDataSync: 'VeBus.MissingDataSync',
      BusTicketPointTopic: 'VeBus.BusTicketPointTopic',
      StartTripTopic: 'VeBus.StartTripTopic',
      EndTripTopic: 'VeBus.EndTripTopic',
      GMT: 7,
      PORT: 3505,
      MQ_TOPIC_LOG: 'Vebus.Log'
    },
    env_production: {
      BOT_TOKEN: '6439712622:AAGRWQow3jXzof9Ss-HhqLq6kQwslAIKmig',
      BOT_CHAT_ID: '-1001901444413',
      DB_HOST_CONFIG: '172.16.10.83',
      DB_PORT_CONFIG: 3306,
      DB_NAME_CONFIG: 'vebus_config',
      DB_USER_CONFIG: 'vdsi',
      DB_PASS_CONFIG: 'Vdsi@2023',
      DB_HOST_WRITE: '172.16.10.83',
      DB_PORT_WRITE: 3306,
      DB_NAME_WRITE: 'vebus_log',
      DB_USER_WRITE: 'vdsi',
      DB_PASS_WRITE: 'Vdsi@2023',
      DB_HOST_READ: '172.16.10.83',
      DB_PORT_READ: '3306',
      DB_NAME_READ: 'vebus_log',
      DB_USER_READ: 'vdsi',
      DB_PASS_READ: 'Vdsi@2023',
      DB_HOST_INVOICE: '172.16.10.83',
      DB_PORT_INVOICE: '3306',
      DB_NAME_INVOICE: 'vebus_invoice',
      DB_USER_INVOICE: 'vdsi',
      DB_PASS_INVOICE: 'Vdsi@2023',
      ENV: 'production',
      API_KEY: '980alsdfja!^&%%KJBKuioalsdfasdio',
      RABBITMQ_HOST: '172.16.10.60',
      RABBITMQ_PORT: 5672,
      RABBITMQ_USERNAME: 'vdsi_queue',
      RABBITMQ_PASSWORD: 'Vdsi@1234567890',
      OperatorSyncBusTicketStartEndPointTopic: 'VeBus.OperatorSync.BusTicketStartEndPointTopic_V1',
      OperatorSyncBusTicketPointTopic: 'VeBus.OperatorSync.BusTicketPointTopic_V1',
      OperatorSyncTopic: 'VeBus.OperatorSyncTopic_V1',
      InvoiceSyncTopicB1: 'VeBus.InvoiceSyncB1_V1',
      MissingDataSync: 'VeBus.MissingDataSync',
      BusTicketPointTopic: 'VeBus.BusTicketPointTopic',
      StartTripTopic: 'VeBus.StartTripTopic',
      EndTripTopic: 'VeBus.EndTripTopic',
      GMT: 7,
      PORT: 3503,
      MQ_TOPIC_LOG: 'Vebus.Log'
    },
  }],
  deploy: {
    development: {
      user: 'vdsi',
      host: '192.168.1.215',
      ref: 'origin/develop',
      repo: 'git@github.com:Tuanthe140171/apiBusticket.git',
      path: '/home/vdsi/apiBusticketV2',
      ssh_options: ['PasswordAuthentication=no', 'StrictHostKeyChecking=no'],
      'pre-deploy-local': '',
      'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env development',
      'pre-setup': '',
    },
    production: {
      user: 'vdsi',
      host: ['172.16.10.51', '172.16.10.52', '172.16.10.53'],
      ref: 'origin/main',
      repo: 'git@github.com:Tuanthe140171/apiBusticket.git',
      path: '/home/vdsi/apiBusticketV3',
      ssh_options: ['PasswordAuthentication=no', 'StrictHostKeyChecking=no'],
      'pre-deploy-local': '',
      'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env production',
      'pre-setup': 'mkdir -p /home/vdsi/apiBusticketV3 && rm -rf /home/vdsi/apiBusticketV3',
    }
  }
};
